const CATEGORIES_ACTION_TYPE = {
    SET_CATEGORIES: 'SET_CATEGORIES',
    FETCH_CATEGORIES_START: 'FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAIL: 'FETCH_CATEGORIES_FAIL',
};

export default CATEGORIES_ACTION_TYPE;